// Major Indian Railway Trains - Number and Name
// This is a comprehensive list of popular trains for autocomplete suggestions

export interface TrainInfo {
  number: string
  name: string
}

export const INDIAN_TRAINS: TrainInfo[] = [
  // Rajdhani Express
  { number: '12301', name: 'Howrah Rajdhani Express' },
  { number: '12302', name: 'New Delhi Rajdhani Express' },
  { number: '12303', name: 'Poorva Express' },
  { number: '12305', name: 'Howrah Rajdhani Express (via Patna)' },
  { number: '12309', name: 'Rajendra Nagar Rajdhani Express' },
  { number: '12313', name: 'Sealdah Rajdhani Express' },
  { number: '12431', name: 'Trivandrum Rajdhani Express' },
  { number: '12433', name: 'Chennai Rajdhani Express' },
  { number: '12435', name: 'Dibrugarh Rajdhani Express' },
  { number: '12437', name: 'Secunderabad Rajdhani Express' },
  { number: '12439', name: 'Ranchi Rajdhani Express' },
  { number: '12441', name: 'Bilaspur Rajdhani Express' },
  { number: '12443', name: 'Haldia Rajdhani Express' },
  { number: '12951', name: 'Mumbai Rajdhani Express' },
  { number: '12953', name: 'August Kranti Rajdhani Express' },
  { number: '12955', name: 'Jaipur Superfast Express (Mumbai Rajdhani)' },
  { number: '12957', name: 'Swarna Jayanti Rajdhani Express' },
  { number: '12309', name: 'Patna Rajdhani Express' },

  // Shatabdi Express
  { number: '12001', name: 'Bhopal Shatabdi Express' },
  { number: '12002', name: 'New Delhi Shatabdi Express (from Bhopal)' },
  { number: '12003', name: 'Lucknow Swarna Shatabdi Express' },
  { number: '12005', name: 'Kalka Shatabdi Express' },
  { number: '12007', name: 'Chennai Shatabdi Express' },
  { number: '12009', name: 'Ahmedabad Shatabdi Express' },
  { number: '12011', name: 'Kalka Shatabdi Express' },
  { number: '12013', name: 'Amritsar Shatabdi Express' },
  { number: '12015', name: 'Ajmer Shatabdi Express' },
  { number: '12017', name: 'Dehradun Shatabdi Express' },
  { number: '12019', name: 'Howrah Shatabdi Express' },
  { number: '12021', name: 'Howrah Jan Shatabdi Express' },
  { number: '12023', name: 'Patna Jan Shatabdi Express' },
  { number: '12025', name: 'Pune Shatabdi Express' },
  { number: '12027', name: 'Chennai Shatabdi Express' },
  { number: '12029', name: 'Swarna Shatabdi Express' },
  { number: '12031', name: 'Amritsar Shatabdi Express' },
  { number: '12033', name: 'Kanpur Shatabdi Express' },
  { number: '12035', name: 'Chandigarh Shatabdi Express' },
  { number: '12039', name: 'Kathgodam Shatabdi Express' },
  { number: '12040', name: 'New Delhi Shatabdi Express (from Kathgodam)' },

  // Vande Bharat Express
  { number: '22435', name: 'Varanasi Vande Bharat Express' },
  { number: '22436', name: 'New Delhi Vande Bharat Express (from Varanasi)' },
  { number: '22439', name: 'Ahmedabad Vande Bharat Express' },
  { number: '22440', name: 'Mumbai Vande Bharat Express (from Ahmedabad)' },
  { number: '20601', name: 'Chennai Vande Bharat Express' },
  { number: '20602', name: 'Mysuru Vande Bharat Express' },
  { number: '20603', name: 'Secunderabad Vande Bharat Express' },
  { number: '20604', name: 'Visakhapatnam Vande Bharat Express' },
  { number: '20605', name: 'Nagpur Vande Bharat Express' },
  { number: '20607', name: 'Shirdi Vande Bharat Express' },
  { number: '20609', name: 'Rani Kamalapati Vande Bharat Express' },
  { number: '20611', name: 'Goa Vande Bharat Express' },
  { number: '20613', name: 'Jaipur Vande Bharat Express' },
  { number: '20615', name: 'Katra Vande Bharat Express' },
  { number: '20617', name: 'Chandigarh Vande Bharat Express' },
  { number: '20619', name: 'Una Vande Bharat Express' },
  { number: '20621', name: 'Dehradun Vande Bharat Express' },
  { number: '20623', name: 'Patna Vande Bharat Express' },
  { number: '20625', name: 'Ranchi Vande Bharat Express' },
  { number: '20627', name: 'Gorakhpur Vande Bharat Express' },
  { number: '20629', name: 'Puri Vande Bharat Express' },
  { number: '20631', name: 'Visakhapatnam Vande Bharat Express (from Secunderabad)' },
  { number: '20633', name: 'Tirunelveli Vande Bharat Express' },
  { number: '20635', name: 'Coimbatore Vande Bharat Express' },
  { number: '20637', name: 'Thiruvananthapuram Vande Bharat Express' },
  { number: '20639', name: 'Mangaluru Vande Bharat Express' },
  { number: '20641', name: 'Kasaragod Vande Bharat Express' },
  { number: '20643', name: 'Dharwad Vande Bharat Express' },

  // Duronto Express
  { number: '12213', name: 'Mumbai Duronto Express' },
  { number: '12245', name: 'Howrah Duronto Express' },
  { number: '12247', name: 'Chennai Duronto Express' },
  { number: '12249', name: 'Ahmedabad Duronto Express' },
  { number: '12259', name: 'Sealdah Duronto Express' },
  { number: '12261', name: 'Howrah Duronto Express (CST)' },
  { number: '12263', name: 'Pune Duronto Express' },
  { number: '12267', name: 'Mumbai Duronto Express (AC)' },
  { number: '12269', name: 'Chennai Duronto Express (Hazrat Nizamuddin)' },
  { number: '12273', name: 'Howrah Duronto Express (New Delhi)' },
  { number: '12283', name: 'Ernakulam Duronto Express' },
  { number: '12285', name: 'Secunderabad Duronto Express' },
  { number: '12289', name: 'Mumbai Nagpur Duronto Express' },
  { number: '12291', name: 'Patna Duronto Express' },

  // Garib Rath Express
  { number: '12201', name: 'Mumbai LTT Garib Rath Express' },
  { number: '12203', name: 'Saharsa Garib Rath Express' },
  { number: '12205', name: 'Nandan Kanan Garib Rath Express' },
  { number: '12207', name: 'Jammu Tawi Garib Rath Express' },
  { number: '12209', name: 'Kanpur Garib Rath Express' },
  { number: '12211', name: 'Muzaffarpur Garib Rath Express' },
  { number: '12215', name: 'Delhi Garib Rath Express' },

  // Tejas Express
  { number: '82501', name: 'Mumbai CSMT Ahmedabad Tejas Express' },
  { number: '82502', name: 'Ahmedabad Mumbai CSMT Tejas Express' },
  { number: '82901', name: 'Mumbai CSMT Goa Tejas Express' },
  { number: '82902', name: 'Goa Mumbai CSMT Tejas Express' },
  { number: '22119', name: 'Mumbai CSMT Karmali Tejas Express' },
  { number: '22120', name: 'Karmali Mumbai CSMT Tejas Express' },
  { number: '22121', name: 'Lucknow New Delhi Tejas Express' },
  { number: '22122', name: 'New Delhi Lucknow Tejas Express' },

  // Major Superfast / Express Trains
  { number: '12621', name: 'Tamil Nadu Express' },
  { number: '12622', name: 'Tamil Nadu Express (Return)' },
  { number: '12625', name: 'Kerala Express' },
  { number: '12626', name: 'Kerala Express (Return)' },
  { number: '12627', name: 'Karnataka Express' },
  { number: '12628', name: 'Karnataka Express (Return)' },
  { number: '12629', name: 'Karnataka Sampark Kranti Express' },
  { number: '12723', name: 'Telangana Express' },
  { number: '12724', name: 'Telangana Express (Return)' },
  { number: '12839', name: 'Chennai Mail' },
  { number: '12840', name: 'Chennai Mail (Return)' },
  { number: '12841', name: 'Coromandel Express' },
  { number: '12842', name: 'Coromandel Express (Return)' },
  { number: '12859', name: 'Gitanjali Express' },
  { number: '12860', name: 'Gitanjali Express (Return)' },
  { number: '12903', name: 'Golden Temple Mail' },
  { number: '12904', name: 'Golden Temple Mail (Return)' },
  { number: '12259', name: 'Sealdah Duronto Express' },
  { number: '12561', name: 'Swatantrta Senani Express' },
  { number: '12801', name: 'Purushottam Express' },
  { number: '12802', name: 'Purushottam Express (Return)' },
  { number: '12381', name: 'Poorva Express' },
  { number: '12382', name: 'Poorva Express (Return)' },
  { number: '12311', name: 'Kalka Mail' },
  { number: '12312', name: 'Kalka Mail (Return)' },
  { number: '12049', name: 'Gatimaan Express' },
  { number: '12050', name: 'Gatimaan Express (Return)' },
  { number: '12423', name: 'Dibrugarh Town Rajdhani Express' },
  { number: '12424', name: 'New Delhi Rajdhani Express (from Dibrugarh)' },
  { number: '15635', name: 'Guwahati Express' },
  { number: '15636', name: 'Guwahati Express (Return)' },
  { number: '12615', name: 'Grand Trunk Express' },
  { number: '12616', name: 'Grand Trunk Express (Return)' },
  { number: '16527', name: 'Yesvantpur Kochuveli Express' },
  { number: '12617', name: 'Mangala Lakshadweep Express' },
  { number: '12618', name: 'Mangala Lakshadweep Express (Return)' },
  { number: '12163', name: 'Dadar Chennai Express' },
  { number: '12164', name: 'Chennai Dadar Express' },
  { number: '12101', name: 'Jnaneswari Super Deluxe Express' },
  { number: '12102', name: 'Jnaneswari Super Deluxe Express (Return)' },
  { number: '11301', name: 'Udyan Express' },
  { number: '11302', name: 'Udyan Express (Return)' },
  { number: '12627', name: 'Karnataka Express' },
  { number: '12809', name: 'Mumbai Howrah Mail' },
  { number: '12810', name: 'Howrah Mumbai Mail' },
  { number: '12137', name: 'Punjab Mail' },
  { number: '12138', name: 'Punjab Mail (Return)' },
  { number: '12139', name: 'Sewagram Express' },
  { number: '12140', name: 'Sewagram Express (Return)' },
  { number: '12105', name: 'Vidarbha Express' },
  { number: '12106', name: 'Vidarbha Express (Return)' },
  { number: '11013', name: 'Coimbatore Express (Mumbai)' },
  { number: '11014', name: 'Coimbatore Express (Return)' },
  { number: '16345', name: 'Thiruvananthapuram Express' },
  { number: '16346', name: 'Thiruvananthapuram Express (Return)' },
  { number: '12657', name: 'Chennai Central Mail' },
  { number: '12658', name: 'Chennai Central Mail (Return)' },
  { number: '12697', name: 'Trivandrum Chennai Superfast Express' },
  { number: '12698', name: 'Chennai Trivandrum Superfast Express' },
  { number: '12659', name: 'Gurudev Express' },
  { number: '12660', name: 'Gurudev Express (Return)' },
  { number: '12723', name: 'Telangana Express' },
  { number: '15015', name: 'Gorakhpur Yesvantpur Express' },
  { number: '15016', name: 'Yesvantpur Gorakhpur Express' },
  { number: '12505', name: 'Northeast Express' },
  { number: '12506', name: 'Northeast Express (Return)' },
  { number: '12487', name: 'Seemanchal Express' },
  { number: '12488', name: 'Seemanchal Express (Return)' },
  { number: '15483', name: 'Mahananda Express' },
  { number: '15484', name: 'Mahananda Express (Return)' },
  { number: '12343', name: 'Darjeeling Mail' },
  { number: '12344', name: 'Darjeeling Mail (Return)' },
  { number: '12345', name: 'Saraighat Express' },
  { number: '12346', name: 'Saraighat Express (Return)' },
  { number: '12367', name: 'Vikramshila Express' },
  { number: '12368', name: 'Vikramshila Express (Return)' },
  { number: '12369', name: 'Kumbha Express' },
  { number: '12370', name: 'Kumbha Express (Return)' },
  { number: '12553', name: 'Vaishali Express' },
  { number: '12554', name: 'Vaishali Express (Return)' },
  { number: '12555', name: 'Gorakhdham Express' },
  { number: '12556', name: 'Gorakhdham Express (Return)' },
  { number: '12557', name: 'Sapt Kranti Express' },
  { number: '12558', name: 'Sapt Kranti Express (Return)' },
  { number: '12559', name: 'Shiv Ganga Express' },
  { number: '12560', name: 'Shiv Ganga Express (Return)' },
  { number: '12393', name: 'Sampoorna Kranti Express' },
  { number: '12394', name: 'Sampoorna Kranti Express (Return)' },
  { number: '12397', name: 'Mahabodhi Express' },
  { number: '12398', name: 'Mahabodhi Express (Return)' },

  // Humsafar Express
  { number: '22807', name: 'Santragachi Chennai AC Humsafar Express' },
  { number: '22808', name: 'Chennai Santragachi AC Humsafar Express' },
  { number: '12595', name: 'Gorakhpur Anand Vihar Humsafar Express' },
  { number: '12596', name: 'Anand Vihar Gorakhpur Humsafar Express' },

  // Double Decker
  { number: '12985', name: 'Jaipur Double Decker Express' },
  { number: '12986', name: 'New Delhi Double Decker Express' },

  // Sampark Kranti Express
  { number: '12649', name: 'Karnataka Sampark Kranti Express' },
  { number: '12650', name: 'Karnataka Sampark Kranti Express (Return)' },
  { number: '12707', name: 'AP Sampark Kranti Express' },
  { number: '12708', name: 'AP Sampark Kranti Express (Return)' },
  { number: '12919', name: 'Gujarat Sampark Kranti Express' },
  { number: '12920', name: 'Gujarat Sampark Kranti Express (Return)' },

  // Jan Shatabdi
  { number: '12051', name: 'Madurai Jan Shatabdi Express' },
  { number: '12052', name: 'Chennai Jan Shatabdi Express' },
  { number: '12053', name: 'Howrah Jan Shatabdi Express' },
  { number: '12054', name: 'New Delhi Jan Shatabdi Express' },
  { number: '12055', name: 'Dehradun Jan Shatabdi Express' },
  { number: '12056', name: 'New Delhi Jan Shatabdi Express (from Dehradun)' },
  { number: '12057', name: 'Chandigarh Jan Shatabdi Express' },
  { number: '12058', name: 'New Delhi Jan Shatabdi Express (from Chandigarh)' },
  { number: '12059', name: 'Kota Jan Shatabdi Express' },
  { number: '12060', name: 'New Delhi Jan Shatabdi Express (from Kota)' },

  // Namma Metro / Popular South Indian Trains
  { number: '12677', name: 'Ernakulam Intercity Express' },
  { number: '12678', name: 'Ernakulam Intercity Express (Return)' },
  { number: '16525', name: 'Bangalore Kanyakumari Island Express' },
  { number: '16526', name: 'Kanyakumari Bangalore Island Express' },
  { number: '12507', name: 'Guwahati Trivandrum Express' },
  { number: '12508', name: 'Trivandrum Guwahati Express' },
  { number: '16315', name: 'Kochuveli Express' },
  { number: '16316', name: 'Kochuveli Express (Return)' },
  { number: '16301', name: 'Shoranur Trivandrum Express' },
  { number: '16302', name: 'Trivandrum Shoranur Express' },
  { number: '12601', name: 'Chennai Mangalore Mail' },
  { number: '12602', name: 'Mangalore Chennai Mail' },
  { number: '12607', name: 'Lalbagh Express' },
  { number: '12608', name: 'Lalbagh Express (Return)' },
  { number: '12609', name: 'Bengaluru Chennai Brindavan Express' },
  { number: '12610', name: 'Chennai Bengaluru Brindavan Express' },

  // Amrit Bharat Express
  { number: '20501', name: 'Amrit Bharat Express (Darbhanga)' },
  { number: '20503', name: 'Amrit Bharat Express (Ayodhya)' },

  // Popular Western Region
  { number: '12009', name: 'Mumbai Ahmedabad Shatabdi Express' },
  { number: '12010', name: 'Ahmedabad Mumbai Shatabdi Express' },
  { number: '19011', name: 'Gujarat Express' },
  { number: '19012', name: 'Gujarat Express (Return)' },
  { number: '12901', name: 'Gujarat Mail' },
  { number: '12902', name: 'Gujarat Mail (Return)' },
  { number: '22945', name: 'Saurashtra Mail' },
  { number: '22946', name: 'Saurashtra Mail (Return)' },
  { number: '19115', name: 'Bhuj Express' },
  { number: '19116', name: 'Bhuj Express (Return)' },
  { number: '16209', name: 'Mysore Ajmer Express' },
  { number: '16210', name: 'Ajmer Mysore Express' },
]

export function searchTrains(query: string): TrainInfo[] {
  if (!query || query.length < 1) return []
  const q = query.toLowerCase()
  return INDIAN_TRAINS.filter(
    t => t.number.includes(q) || t.name.toLowerCase().includes(q)
  )
}
